In [1]:
# import the library
import googlemaps
import json
import pprint
import time
import pandas as pd
import numpy as np
import re

In [2]:
API_KEY = 'AIzaSyAXb1CyMDuAKkbk25LPIo9_XGSMGioLhEU'

In [5]:
data = pd.read_csv(  r"../_data/peru_excel_clean.csv")

In [11]:
df1 = data[ data.iloc[ :, 3 ].notnull() ].copy()

In [14]:
df1.head()

,Departamento,Provincia,Distrito,Dirección
0,AMAZONAS,AMAZONAS,CHACHAPOYAS,Jirón Triunfo Nº 903 1er piso
1,AMAZONAS,Rodriguez de Mendoza,San Nicolás,Jirón Victor Mori Nº 204 San Nicolás
2,AMAZONAS,BAGUA,BAGUA,Calle Junín S/N
3,AMAZONAS,BONGARA,JAZAN,Avenida marginal N° 100 Pedro Ruíz
4,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,Jirón Simón Bolivar N° 545

In [15]:
def join_columns( row_series ):
    
    
    return address

In [13]:
def get_results( result_api ):
    
    try:
        lat = result_api[0]['geometry']['location']['lat']
        lon = result_api[0]['geometry']['location']['lng']   
    except:
        lat = np.nan
        lon = np.nan
    
    return ( lat, lon )

In [52]:
def geo_reniec( row_series ):
    
    address = f"{row_series['Departamento']}, {row_series['Provincia']}, {row_series['Distrito']}, {row_series['Dirección']}"
    
    # Set Geolocation
    gmaps = googlemaps.Client( key = 'AIzaSyD_4E6Hd-fYECy3mZ4asxN23JjIstvLdoE' )
    result_api = gmaps.geocode( address , region = 'PE' )
    
    # Information
    try:
        lat = result_api[0]['geometry']['location']['lat']
        lon = result_api[0]['geometry']['location']['lng']   
    except:
        lat = np.nan
        lon = np.nan
    
    return ( address, lat, lon )

In [46]:
df2 = df1.sample( frac = 0.05 ).copy()

In [53]:
df2['results'] = df2.apply( lambda x: geo_reniec( x )  , axis = 1 )

In [ ]:
df2

In [ ]:
pd.DataFrame( df2.results.tolist()  )

In [55]:
df2[['addres', 'lat', 'lng']] = pd.DataFrame( df2.results.tolist() ,  index = df2.index )

In [56]:
df2

,Departamento,Provincia,Distrito,Dirección,results,lat,lng,addres
215,PUNO,PUNO,PUNO,Jirón Arequipa Nº 1145 Puno,"(PUNO, PUNO, PUNO, Jirón Arequipa Nº 1145 Puno...",-15.844400,-70.023201,"PUNO, PUNO, PUNO, Jirón Arequipa Nº 1145 Puno"
151,LIMA,LIMA,CIENEGUILLA,Av. San Martín Lt 15 Mz D Zona D Cpr Tambo Viejo,"(LIMA, LIMA, CIENEGUILLA, Av. San Martín Lt 15...",-12.014774,-76.885043,"LIMA, LIMA, CIENEGUILLA, Av. San Martín Lt 15 ..."
58,CAJAMARCA,JAEN,PUCARA,Ca. Lindo 548,"(CAJAMARCA, JAEN, PUCARA, Ca. Lindo 548, -6.04...",-6.040897,-79.129826,"CAJAMARCA, JAEN, PUCARA, Ca. Lindo 548"
0,AMAZONAS,AMAZONAS,CHACHAPOYAS,Jirón Triunfo Nº 903 1er piso,"(AMAZONAS, AMAZONAS, CHACHAPOYAS, Jirón Triunf...",-6.230742,-77.871960,"AMAZONAS, AMAZONAS, CHACHAPOYAS, Jirón Triunfo..."
10,ANCASH,SANTA,SANTA,Jirón Ladislao Espinar No.401 y Esquina de Enr...,"(ANCASH, SANTA, SANTA, Jirón Ladislao Espinar ...",-9.072811,-78.593487,"ANCASH, SANTA, SANTA, Jirón Ladislao Espinar N..."
64,CUSCO,CANCHIS,SICUANI,Av. Tupac Amaru 163 Sicuani,"(CUSCO, CANCHIS, SICUANI, Av. Tupac Amaru 163 ...",-14.266855,-71.225515,"CUSCO, CANCHIS, SICUANI, Av. Tupac Amaru 163 S..."
123,LA LIBERTAD,VIRÚ,VIRÚ,Lt. 8 Mz A Urb. Las Palmeras,"(LA LIBERTAD, VIRÚ, VIRÚ, Lt. 8 Mz A Urb. Las ...",NaN,NaN,"LA LIBERTAD, VIRÚ, VIRÚ, Lt. 8 Mz A Urb. Las P..."
231,SAN MARTIN,MARISCAL CACERES,MARISCAL CACERES,Jr. Eduardo Peña Meza N° 772,"(SAN MARTIN, MARISCAL CACERES, MARISCAL CACERE...",-7.181332,-76.728116,"SAN MARTIN, MARISCAL CACERES, MARISCAL CACERES..."
205,PIURA,SULLANA,SULLANA,Ca. Leoncio Prado Nº 517,"(PIURA, SULLANA, SULLANA, Ca. Leoncio Prado Nº...",-4.895896,-80.692146,"PIURA, SULLANA, SULLANA, Ca. Leoncio Prado Nº 517"
73,CUSCO,URUBAMBA,URUBAMBA,Av. Conchatupa s/n,"(CUSCO, URUBAMBA, URUBAMBA, Av. Conchatupa s/n...",-13.335622,-72.064430,"CUSCO, URUBAMBA, URUBAMBA, Av. Conchatupa s/n"
56,CAJAMARCA,CONTUMAZA,CONTUMAZA,Jr. Miguel Grau Nº 212,"(CAJAMARCA, CONTUMAZA, CONTUMAZA, Jr. Miguel ...",-7.366643,-78.805111,"CAJAMARCA, CONTUMAZA, CONTUMAZA, Jr. Miguel G..."
158,LIMA,LIMA,VILLA EL SALVADOR,Av. Arriba Perú Nº 640 Sector 2. Grupo 7,"(LIMA, LIMA, VILLA EL SALVADOR, Av. Arriba Per...",-12.204490,-76.939520,"LIMA, LIMA, VILLA EL SALVADOR, Av. Arriba Perú..."